### ISSUE TITLE
How did you get into programming?

### ISSUE THREAD

**Issue by sindresorhus** [jdalton/ama#4]

**Comment by jdalton** [comment]
I was the leader of a flight squadron, The Little Monkeys, for an online WWI flight sim called Simguild Flying Circus in ~1998/1999. Since I was the leader I was in charge of creating a web site so I learned HTML and JavaScript to make fancy mouseover image effects and apply glowing text.

<img src=https://cloud.githubusercontent.com/assets/4303/8644008/fbe08a9e-28ef-11e5-9890-e3349a662431.png width=25% height=25%>

<img src=https://cloud.githubusercontent.com/assets/4303/8644010/fef0e81e-28ef-11e5-848a-a88958566a4a.png width=25% height=25%>

<img src=https://cloud.githubusercontent.com/assets/4303/8644101/045a7df0-28f1-11e5-9fdd-b5ebcc0ea226.png width=25% height=25%>
